name: 'Run Swift Tests'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  swift-tests:
    name: 'Swift Tests'
    runs-on: ubuntu-latest
     # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Set up Swift
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.10"
      - name: Get swift version
        run: swift --version

      # Run tests
      - name: Run tests
        run: make test
      - name: Coverage
        run: make coverage
      - name: Upload Code Coverage 
        uses: codecov/codecov-action@v3
        with:
          files: ${{ github.workspace }}/lcov.info